language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - python -m pytest
  - sleep 1
  - sleep 1
  - sleep 1
  - sleep 1
  - sleep 1
  - sleep 1
  - sleep 1
  - sleep 1
  - sleep 1
  - sleep 1
