language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
jobs:
  include:
    - script: python -m pytest
    - script: sleep 30
    - script: sleep 30
    - script: sleep 30
    - script: sleep 30
    - script: sleep 30
    - script: sleep 30
    - script: sleep 30
  
